name: Collect

on:
  schedule:
    - cron:  '*/60 * * * *'

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
    - name: Set date
      run: echo "::set-env name=RUN_DATE::$(date +%F_%H:%M)"
    - uses: actions/checkout@v2
      with: 
        path: 'main'
    - uses: actions/checkout@v2
      with: 
        ref: gh-pages
        path: 'gh-pages'
    - name: Downloads stations data
      run: curl "https://velib-metropole-opendata.smoove.pro/opendata/Velib_Metropole/station_status.json" -o "gh-pages/data/raw/stations/${RUN_DATE}.json"
    - name: Downloads stations list
      run: curl "https://velib-metropole-opendata.smoove.pro/opendata/Velib_Metropole/station_information.json" -o "gh-pages/data/raw/stations.json"
    - name: Create index
      run: main/scripts/create_index.sh gh-pages/data/raw/stations
    - name: Commit
      working-directory: gh-pages
      run: |
        git config --global user.name 'Bot'
        git config --global user.email 'bot@users.noreply.github.com'
        git add .
        git commit -am "Collect Data"
        git push
